language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - laminas-mkdoc-theme

env:
  global:
    - SITE_URL=https://docs.laminas.dev/laminas-json
    - GH_USER_NAME="Matthew Weier O'Phinney"
    - GH_USER_EMAIL=matthew@weierophinney.net
    - GH_REF=github.com/laminas/laminas-json.git
    - secure: "XP/GRTnJ2XM5C4sNDxhMcKpA9g8g8st8VKm9aev01QOQiQYtc8kgpV3L+eb7+juxHD3C6DKjfHliMnmT51PYBzSDi5JTiiECThljSlnOtfaeYQJftys5f94cHt2jFH4JzbbhIGgkMXbpNNCs+/nbL1P8DFju7GfzQM2iDwJJT7RfMlrv3pafRhfADfScIFqH4qEIHXQV0pnclPPsnAmE29PKsKwkt61nxS8j7n6ylFcuZ5e8JbOD92FL2HVVdeiQMPmX0T3ac6HZReS6qsxMvdSas/1+LyFmVSTAhRQnncNtZKOT8QiemPIwaaf/9PQooDMMWPJCn65LaiQ8YKNAes5O7YIyYddQbK0ulyFvfxDrMGW8GuEFj2xVVWQZ1o70+XK19znzCvkv1bCeicrpVxcsq35N7pYZk1HyyJ4ZTkBhNyIPHgKUqomT6uPrXlOLBov5mWcvdgqsa6PGVNlkWpp5Q426lLrHJIV9NS27ZqKq6/tFn3bhkUclknS/U5v/AD7PgaN+lJbFLyKnPeFCIyVqfqiXeKXNC8kez4rDJybvp/oimZzXrNATEyHTnrC3yNo3hJpAX3THES4uC8yVHqBJdCJCIiDt0zkiC9Z/tGXZZsE6Bop4sOtq+bCTpOYNlibfipxXchX/ccGd/4dQoceVGx7i0ETAojPgPd78mtk="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: hhvm

notifications:
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer upload-coverage ; fi
