docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
      - "Basic Usage": basics.md
      - "Advanced Usage": advanced.md
    - Migration:
      - "From v2 to v3": migration/v2-to-v3.md
site_name: laminas-json
site_description: Laminas\Json
repo_url: 'https://github.com/laminas/laminas-json'
